apiVersion: v1
kind: Template
metadata:
  labels:
    app: enmasse
  name: queue-persisted
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: enmasse
      infraType: standard
      infraUuid: ${INFRA_UUID}
      infraNamespace: ${INFRA_NAMESPACE}
    namespace: enmasse-infra
    name: broker-metrics-${INFRA_UUID}
    annotations:
      addressSpace: ${ADDRESS_SPACE}
      cluster_id: ${CLUSTER_ID}
      serviceaccounts.openshift.io/oauth-redirectreference.first: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"broker-metrics-${INFRA_UUID}"}}'
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    labels:
      app: enmasse
      infraType: standard
      infraUuid: ${INFRA_UUID}
      infraNamespace: ${INFRA_NAMESPACE}
    name: enmasse.io:broker-metrics-${INFRA_UUID}
    namespace: enmasse-infra
    annotations: 
      addressSpace: ${ADDRESS_SPACE}
      cluster_id: ${CLUSTER_ID}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:auth-delegator
  subjects:
  - kind: ServiceAccount
    name: broker-metrics-${INFRA_UUID}
    namespace: ${INFRA_NAMESPACE}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      addressSpace: ${ADDRESS_SPACE}
      cluster_id: ${CLUSTER_ID}
    labels:
      app: enmasse
      infraType: standard
      infraUuid: ${INFRA_UUID}
      # TODO Delete this line. It's for testing purposes
      monitoring-key: tenants
    name: ${NAME}
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: broker-metrics-${INFRA_UUID}-tls
  spec:
    ports:
    - name: health
      port: 8080
      protocol: TCP
      targetPort: artemismetrics
    - name: metrics-proxy
      port: 443
      protocol: TCP
      targetPort: proxy
    selector:
      name: ${NAME}
      role: broker
      infraUuid: ${INFRA_UUID}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: enmasse
      role: broker
      infraUuid: ${INFRA_UUID}
    name: broker-metrics-${INFRA_UUID}
    annotations:
      addressSpace: ${ADDRESS_SPACE}
      cluster_id: ${CLUSTER_ID}
  spec:
    port:
      targetPort: metrics-proxy
    tls:
      termination: reencrypt
    to:
      kind: Service
      name: ${NAME}
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      address: ${ADDRESS}
      addressSpace: ${ADDRESS_SPACE}
      cluster_id: ${CLUSTER_ID}
      enmasse.io/cert-cn: broker.${INFRA_UUID}
      enmasse.io/cert-secret: broker-internal-cert.${INFRA_UUID}
    labels:
      app: enmasse
      infraType: standard
      infraUuid: ${INFRA_UUID}
    name: ${NAME}
  spec:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: node-role.enmasse.io/messaging-infra
                  operator: In
                  values:
                    - "true"
    replicas: 1
    serviceName: ${NAME}
    selector:
      matchLabels:
        addresstype: queue
        app: enmasse
        name: ${NAME}
        role: broker
        infraType: standard
        infraUuid: ${INFRA_UUID}
    template:
      metadata:
        annotations:
          address: ${ADDRESS}
          addressSpace: ${ADDRESS_SPACE}
          cluster_id: ${CLUSTER_ID}
          prometheus.io/path: /metrics
          prometheus.io/port: '8080'
          prometheus.io/scrape: 'true'
        labels:
          addresstype: queue
          app: enmasse
          name: ${NAME}
          role: broker
          infraType: standard
          infraUuid: ${INFRA_UUID}
      spec:
        serviceAccountName: broker-metrics-${INFRA_UUID}
        containers:
        - env:
          - name: MESSAGING_SERVICE_HOST
            value: messaging-${INFRA_UUID}
          - name: MESSAGING_SERVICE_PORT_AMQPS_BROKER
            value: 56671
          - name: MESSAGING_SERVICE_PORT_AMQPS_NORMAL
            value: 55671
          - name: INFRA_UUID
            value: ${INFRA_UUID}
          - name: QUEUE_NAME
            value: ${ADDRESS}
          - name: CLUSTER_ID
            value: ${CLUSTER_ID}
          - name: CERT_DIR
            value: /etc/enmasse-certs
          - name: CONNECTOR_IN_NETTY_THREADS
            value: ${BROKER_CONNECTOR_NETTY_THREADS}
          - name: CONNECTOR_OUT_NETTY_THREADS
            value: ${BROKER_CONNECTOR_NETTY_THREADS}
          - name: CONNECTOR_IN_IDLE_TIMEOUT_MS
            value: ${BROKER_CONNECTOR_IDLE_TIMEOUT_MS}
          - name: CONNECTOR_OUT_IDLE_TIMEOUT_MS
            value: ${BROKER_CONNECTOR_IDLE_TIMEOUT_MS}
          - name: ADDRESS_FULL_POLICY
            value: ${BROKER_ADDRESS_FULL_POLICY}
          - name: AUTHENTICATION_SERVICE_HOST
            value: ${AUTHENTICATION_SERVICE_HOST}
          - name: AUTHENTICATION_SERVICE_PORT
            value: ${AUTHENTICATION_SERVICE_PORT}
          - name: AUTHENTICATION_SERVICE_CLIENT_SECRET
            value: ${AUTHENTICATION_SERVICE_CLIENT_SECRET}
          - name: AUTHENTICATION_SERVICE_SASL_INIT_HOST
            value: ${AUTHENTICATION_SERVICE_SASL_INIT_HOST}
          - name: AMQ_NAME
            value: serverData
          - name: HOME
            value: /var/run/artemis/split-1/
          image: ${BROKER_IMAGE}
          imagePullPolicy: ${IMAGE_PULL_POLICY}
          command:
          - /opt/apache-artemis/custom/bin/launch-broker.sh
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - $ARTEMIS_HOME/custom/bin/probe.sh
            initialDelaySeconds: 300
          name: broker
          ports:
          - containerPort: 5673
            name: amqp
          - containerPort: 8161
            name: jolokia
          - containerPort: 8080
            name: artemismetrics
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - $ARTEMIS_HOME/custom/bin/probe.sh
            initialDelaySeconds: 10
          resources:
            limits:
              memory: ${BROKER_MEMORY_LIMIT}
            requests:
              memory: ${BROKER_MEMORY_LIMIT}
          volumeMounts:
          - mountPath: /var/run/artemis
            name: data
          - mountPath: /etc/prometheus-config
            name: broker-prometheus-config
            readOnly: true
          - mountPath: /opt/apache-artemis/custom
            name: broker-custom
            readOnly: false
        - args:
          - --provider=openshift
          - --https-address=:8443
          - --http-address=
          - --email-domain=*
          - --upstream=http://localhost:8080/
          - --openshift-service-account=broker-metrics-${INFRA_UUID}
          - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
          - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb":"get"}}'
          - --tls-cert=/etc/tls/private/tls.crt
          - --tls-key=/etc/tls/private/tls.key
          - --cookie-secret=SECRET
          - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
          - -openshift-ca=/etc/pki/tls/cert.pem
          - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          image: openshift/oauth-proxy:latest
          name: oauth-proxy
          ports:
          - containerPort: 8443
            name: proxy
            protocol: TCP
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/tls/private
            name: broker-metrics-tls
        initContainers:
        - env:
          - name: MESSAGING_SERVICE_HOST
            value: messaging-${INFRA_UUID}
          - name: MESSAGING_SERVICE_PORT_AMQPS_BROKER
            value: 56671
          - name: MESSAGING_SERVICE_PORT_AMQPS_NORMAL
            value: 55671
          - name: QUEUE_SCHEDULER_SERVICE_HOST
            value: queue-scheduler-${INFRA_UUID}
          - name: QUEUE_SCHEDULER_SERVICE_PORT
            value: 5672
          - name: INFRA_UUID
            value: ${INFRA_UUID}
          - name: QUEUE_NAME
            value: ${ADDRESS}
          - name: CLUSTER_ID
            value: ${CLUSTER_ID}
          - name: CONNECTOR_IN_NETTY_THREADS
            value: ${BROKER_CONNECTOR_NETTY_THREADS}
          - name: CONNECTOR_OUT_NETTY_THREADS
            value: ${BROKER_CONNECTOR_NETTY_THREADS}
          - name: CONNECTOR_IN_IDLE_TIMEOUT_MS
            value: ${BROKER_CONNECTOR_IDLE_TIMEOUT_MS}
          - name: CONNECTOR_OUT_IDLE_TIMEOUT_MS
            value: ${BROKER_CONNECTOR_IDLE_TIMEOUT_MS}
          - name: GLOBAL_MAX_SIZE
            value: ${BROKER_GLOBAL_MAX_SIZE}
          - name: ADDRESS_FULL_POLICY
            value: ${BROKER_ADDRESS_FULL_POLICY}
          - name: AUTHENTICATION_SERVICE_HOST
            value: ${AUTHENTICATION_SERVICE_HOST}
          - name: AUTHENTICATION_SERVICE_PORT
            value: ${AUTHENTICATION_SERVICE_PORT}
          - name: AUTHENTICATION_SERVICE_CLIENT_SECRET
            value: ${AUTHENTICATION_SERVICE_CLIENT_SECRET}
          - name: AUTHENTICATION_SERVICE_SASL_INIT_HOST
            value: ${AUTHENTICATION_SERVICE_SASL_INIT_HOST}
          - name: AMQ_NAME
            value: serverData
          - name: HOME
            value: /var/run/artemis/split-1/
          image: ${BROKER_PLUGIN_IMAGE}
          imagePullPolicy: ${IMAGE_PULL_POLICY}
          name: broker-plugin
          volumeMounts:
          - mountPath: /etc/enmasse-certs
            name: broker-internal-cert
            readOnly: true
          - mountPath: /etc/authservice-ca
            name: authservice-ca
            readOnly: true
          - mountPath: /etc/prometheus-config
            name: broker-prometheus-config
            readOnly: true
          - mountPath: /opt/apache-artemis/custom
            name: broker-custom
            readOnly: false
        volumes:
        - name: broker-custom
          emptyDir: {}
        - name: authservice-ca
          secret:
            secretName: authservice-ca.${INFRA_UUID}
        - name: broker-internal-cert
          secret:
            secretName: broker-internal-cert.${INFRA_UUID}
        - configMap:
            name: broker-prometheus-config
          name: broker-prometheus-config
        - name: broker-metrics-tls
          secret:
            defaultMode: 420
            secretName: broker-metrics-${INFRA_UUID}-tls
    volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        annotations:
          addressSpace: ${ADDRESS_SPACE}
          cluster_id: ${CLUSTER_ID}
        labels:
          app: enmasse
          infraType: standard
          infraUuid: ${INFRA_UUID}
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: ${BROKER_STORAGE_CAPACITY}
parameters:
- name: INFRA_UUID
  description: UUID to use for infrastructure
  required: true
- description: Storage capacity required for volume claims
  name: BROKER_STORAGE_CAPACITY
  value: 2Gi
- description: A valid addressSpace name for the address Space
  name: ADDRESS_SPACE
  required: true
- description: A valid name for the deployment
  name: NAME
  required: true
- description: A valid group id for the deployment
  name: CLUSTER_ID
  required: true
- description: The address to use for the queue
  name: ADDRESS
  value: ''
- description: The hostname of the authentication service used by this address
    space
  name: AUTHENTICATION_SERVICE_HOST
  required: true
- description: The port of the authentication service used by this address space
  name: AUTHENTICATION_SERVICE_PORT
  required: true
- description: The secret to use for validating authentication service cert
  name: AUTHENTICATION_SERVICE_CA_SECRET
  required: true
- description: The client cert to use as identity against authentication service
  name: AUTHENTICATION_SERVICE_CLIENT_SECRET
- description: The hostname to use in sasl init
  name: AUTHENTICATION_SERVICE_SASL_INIT_HOST
- description: Address full policy
  name: BROKER_ADDRESS_FULL_POLICY
  value: FAIL
- description: Memory limits for container
  name: BROKER_MEMORY_LIMIT
  value: 512Mi
- description: Global max size for all addresses in broker. Cannot be larger than
    a quarter of BROKER_MEMORY_LIMIT
  name: BROKER_GLOBAL_MAX_SIZE
  value: "-1"
- name: BROKER_CONNECTOR_NETTY_THREADS
  description: Number of threads to allocate to connectors
  value: "4"
- name: BROKER_CONNECTOR_IDLE_TIMEOUT_MS
  description: Idle timeout set for connectors
  value: "16000"
- name: IMAGE_PULL_POLICY
  description: Image Pull Policy
  value: ${env.IMAGE_PULL_POLICY}
- name: BROKER_IMAGE
  description: Broker Image
  value: ${env.BROKER_IMAGE}
- name: BROKER_PLUGIN_IMAGE
  description: Broker Plugin Image
  value: ${env.BROKER_PLUGIN_IMAGE}
- name: INFRA_NAMESPACE
  description: The namespace of the enmass infrastructure
  value: ${env.INFRA_NAMESPACE}

