#!/usr/bin/env python

import os

from jinja2 import Environment, FileSystemLoader, Template

fh_services = [
    {'name': 'address-space-controller', 'checks': ['ping', 'health'], 'hostgroups': ['core']},
    {'name': 'api-server', 'checks': ['ping', 'health'], 'hostgroups': ['core']}
]

rhmap_admin_email = os.getenv('RHMAP_ADMIN_EMAIL', 'root@localhost')
rhmap_router_dns = os.getenv('RHMAP_ROUTER_DNS', 'localhost')
rhmap_hostgroups = os.getenv('RHMAP_HOSTGROUPS', 'core')

jenkins_host = os.getenv('JENKINS_SERVICE_HOST')
jenkins_port = os.getenv('JENKINS_SERVICE_PORT')
jenkins_user = os.getenv('JENKINS_USER')
jenkins_pass = os.getenv('JENKINS_PASS')

if rhmap_hostgroups == 'digger':
    platforms = os.getenv('PLATFORMS')
    if 'android' in platforms:
        check_android = True
    if 'ios' in platforms:
        check_mac = True



template_file = '/opt/rhmap/fhservices.cfg.j2'
nagios_config_filename = '/etc/nagios/conf.d/fhservices.cfg'

template_basename = os.path.basename(template_file)
template_dirname = os.path.dirname(template_file)

j2env = Environment(loader=FileSystemLoader(template_dirname), trim_blocks=True)
j2template = j2env.get_template(template_basename)

j2renderedouput = j2template.render(fh_services=fh_services,
                                    rhmap_hostgroups=rhmap_hostgroups,
                                    rhmap_router_dns=rhmap_router_dns,
                                    rhmap_admin_email=rhmap_admin_email)

with open(nagios_config_filename, 'wb') as nagios_config_file:
    nagios_config_file.write(j2renderedouput)
