#!/usr/bin/bash

# Add nagios dirs
mkdir -p /var/log/nagios/archives \
      /var/log/nagios/rw \
      /var/log/nagios/spool/checkresults

set -o errexit
set -o nounset
set -o pipefail

# Add nagios user
htpasswd -c -b -s /etc/nagios/passwd ${NAGIOS_USER} ${NAGIOS_PASSWORD}

# Grant user admin permissions
sed -i "/^authorized_for/ s/$/,${NAGIOS_USER}/" /etc/nagios/cgi.cfg

# Generate command config
/opt/rhmap/make-nagios-commands-cfg

# Generate fhservices config
/opt/rhmap/make-nagios-fhservices-cfg

exec /usr/bin/supervisord -c /etc/supervisord.conf
