apiVersion: v1
kind: Service
metadata:
  name: address-space-controller
  labels:
    app: enmasse
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    component: address-space-controller
  type: ClusterIP